# Generated by Django 6.1 on 2026-09-22 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_representativeapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='representative',
            name='coverage_area',
            field=models.CharField(blank=True, help_text="The area/routes this representative serves, e.g. 'Dhaka campus routes'.", max_length=255),
        ),
        migrations.CreateModel(
            name='RepresentativeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='accounts.representative')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
