# Generated by Django 6.1 on 2026-08-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerequest',
            old_name='description',
            new_name='details',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='category',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='contact_number',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='preferred_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='service_title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
