# Generated by Django 6.1 on 2026-09-05 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_representative_firebase_uid'),
        ('tasks', '0002_rename_description_servicerequest_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('customer_cancelled', 'Customer Cancelled'), ('out_of_area', 'Out of Area'), ('duplicate', 'Duplicate'), ('other', 'Other')], max_length=30)),
                ('note', models.TextField(blank=True)),
                ('dismissed_at', models.DateTimeField(auto_now_add=True)),
                ('representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismissals', to='accounts.representative')),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismissals', to='tasks.servicerequest')),
            ],
        ),
    ]
