# Generated by Django 6.1 on 2026-09-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.CharField(blank=True, help_text='Shown as a one-line subtitle under the title in the app. Keep it short.', max_length=200),
        ),
    ]
