# Generated by Django 6.1 on 2026-09-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon_slug',
            field=models.SlugField(blank=True, help_text="Filename (without extension) of an SVG in tasks/static/service_icons/, e.g. 'building-bank' for building-bank.svg. Pick one from tabler.io/icons — see the README in that folder. Left blank, the app falls back to a colored initial-letter avatar."),
        ),
    ]
