# Generated by Django 6.1 on 2026-10-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_servicerequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, help_text='When the representative confirmed this task — used to compute response time. Cleared if the confirmation is undone.', null=True),
        ),
    ]
